config/routes.rb
Rails.application.routes.draw do
  get 'photos/new'
  get 'photos/show'
  get 'photos/edit'
  get 'photos/update'
  get 'home/index'
  devise_for :users
  root to: 'home#index'
  resources :users do
    resources :albums do
    	resources :photos
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user
  has_many :photos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :album
  belongs_to :user

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :albums
  has_many :photos, through: :albums
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_action :set_album, only: [:show, :edit, :destroy, :update]

  def index
    @albums = Album.all
  end
  
  def new
    @album = current_user.albums.build
  end

  def show
    @photos = Photo.where(album_id: @album.id)
  end

  def edit
    
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to @album
    else
      render 'new'
    end
  end

  def update
    if @album.update(album_params)
      redirect_to user_album_path(current_user, @album)
    else
      render 'edit'
    end
  end

  def destroy
    
  end

  private

  def album_params
    params.require(:album).permit(:name,:user_id)
  end

  def set_album
    @album ||= Album.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@albums = Album.all
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
  before_action :set_album, :set_user
  before_action :set_photo, only: [:show, :edit, :destroy, :update]
  def new
    @photo = @album.photos.build
  end

  def show
  end

  def edit
  end

  def create
    merged_params = photos_params.merge(user_id: params[:user_id])
    @photo = Photo.new(merged_params)
    byebug
    if @photo.save
      redirect_to user_album_path(current_user, @album)
    else
      render 'new'
    end
  end

  def update
    merged_params = photos_params.merge(user_id: params[:user_id])
    if @photo.update(merged_params)
      redirect_to user_album_path(current_user, @album)
    else
      render 'edit'
    end
  end

  def destroy
    
  end

  private

  def photos_params
    params.require(:photo).permit(:image, :tagline, :user_id, :album_id)
  end

  def set_album
    @album ||= Album.find(params[:album_id])
  end

  def set_user
    @user ||= User.find(params[:user_id])
  end

  def set_photo
    @photo ||= Photo.find(params[:id])
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/albums/_form.html.erb
<div class="container">
  <div class="row">
    <h3>Create New Album</h3>
      <%= form_for @album, url: @album.persisted? ? user_album_path(current_user) : user_albums_path(current_user), method: @album.persisted? ? 'patch' : 'post' do |f|%>
        <div class="col-md-12">
            <%= f.label :name %>
            <%= f.text_field :name%>
            <%= f.hidden_field :user_id%>
            <%= f.submit %>
        </div>
      <%end%>
  </div>
</div>

app/views/albums/edit.html.erb
<h3>Edit Album</h3>
<%= render partial: 'form'%>

app/views/albums/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="well sidebar-nav">
        <div class="row">
          <div class="col-md-4">
            <h2>Album name</h2>
          </div>
          <div class="col-md-4">
            <h2>Created at</h2>
          </div>
           <div class="col-md-4">
            <h2>Actions</h2>
          </div>
        </div>
        <div class="row">
            <% @albums.each do |album|%>
            <div class="col-md-4">
              <%= link_to album.name, user_album_path(current_user, album.id)  %>
            </div>
            <div class="col-md-4">
              <%= album.created_at.strftime("%d-%m-%Y")%>
            </div>
            <div class="col-md-4">
              <%= link_to 'Edit', edit_user_album_path(current_user, album)%>
          </div>
            <% end %>
        </div>
      </div><!--/.well -->
    </div><!--/span-->
  </div><!--/row-->

</div> <!-- /container -->

app/views/albums/new.html.erb
<%= render partial: 'form'%>

app/views/albums/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <%= link_to 'Add Photo', new_user_album_photo_path(current_user, @album)%>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <h2> Photo</h2>
    </div>
    <div class="col-md-4">
      <h2>Created at</h2>
    </div>
     <div class="col-md-4">
      <h2>Actions</h2>
    </div>
  </div>
    <% @photos.each do |photo|%>
      <div class="row">
        <div class="col-md-4">
          <%= image_tag photo.image.url, size: '80x50'  %>
        </div>
        <div class="col-md-4">
          <%= photo.created_at.strftime("%d-%m-%Y")%>
        </div>
        <div class="col-md-4">
          <%= link_to 'Edit', edit_user_album_photo_path(current_user, @album, photo)%>
        </div>
      </div>
      <br>
    <% end %>
</div>

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="well sidebar-nav">
        <h3>Dashboard</h3>
           <%= link_to "My Albums", user_albums_path(current_user)  %><br>
          <%= link_to "Create New Album", new_user_album_path(current_user)  %>
        <div class="row">
          <div class="col-md-4">
            <h2>Album name</h2>
          </div>
          <div class="col-md-4">
            <h2>Owner</h2>
          </div>
          <div class="col-md-4">
            <h2>Created at</h2>
          </div>
        <div class="row">
            <% @albums.each do |album|%>
            <div class="col-md-4">
              <%= link_to album.name, user_album_path(current_user, album.id)  %>
            </div>
            <div class="col-md-4">
              <%= album.user.email%>
            </div>
            <div class="col-md-4">
              <%= album.created_at.strftime("%d-%m-%Y")%>
            </div>
            <% end %>
        </div>
      </div><!--/.well -->
    </div><!--/span-->
  </div><!--/row-->

</div> <!-- /container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PhotoShareApp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
   

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path%>">PhotoShareApp</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if current_user %>
              <li><%= link_to "Log Out", destroy_user_session_path  %></li>
            <% else %>
              <li><%= link_to "Login", new_user_session_path  %></li>
              <li><%= link_to "Sign Up", new_user_registration_path  %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <!-- <footer>
        <p>&copy; Company 2020</p>
      </footer> -->

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PhotoShareApp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
   

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">PhotoShareApp</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if current_user %>
              <li><%= link_to "Log Out", destroy_user_session_path  %></li>
            <% else %>
              <li><%= link_to "Login", new_user_session_path  %></li>
              <li><%= link_to "Sign Up", new_user_registration_path  %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <!-- <footer>
        <p>&copy; Company 2020</p>
      </footer> -->

    </div> <!-- /container -->

  </body>
</html>

app/views/photos/_form.html.erb
<div class="container">
  <div class="row">
    <h3>Add Photo to Album</h3>
    <%= form_for @photo, url: @photo.persisted? ? user_album_photo_path(current_user, @album, @photo) : user_album_photos_path(current_user, @album), method: @photo.persisted? ? 'patch' : 'post' do |f|%>
      <div class="row">
        <div class="col-md-12">
            <%= f.label :image %>
            <%= f.file_field :image%>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <%= f.label :tagline %>
            <%= f.text_field :tagline%>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <%= hidden_field_tag :user_id, value: @user.id%>
            <%= f.hidden_field :album_id%>
            <%= f.submit %>
          </div>
        </div>
    <%end%>
  </div>
</div>

app/views/photos/edit.html.erb
<h3>Edit Photo</h3>
<%= render partial: 'form'%>

app/views/photos/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
       <%= render partial: 'form'%>
    </div>
  </div>
</div>

app/views/photos/show.html.erb
<h1>Photos#show</h1>
<p>Find me in app/views/photos/show.html.erb</p>

app/views/photos/update.html.erb
<h1>Photos#update</h1>
<p>Find me in app/views/photos/update.html.erb</p>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => "form-horizontal user" } do |f| %>

  <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <%= f.label :encrypted_password, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :encrypted_password, :class => 'form-control' %>
    </div>
    <%=f.error_span(:encrypted_password) %>
  </div>
  <div class="form-group">
    <%= f.label :reset_password_token, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :reset_password_token, :class => 'form-control' %>
    </div>
    <%=f.error_span(:reset_password_token) %>
  </div>
  <div class="form-group">
    <%= f.label :reset_password_sent_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :reset_password_sent_at, :class => 'form-control' %>
    </div>
    <%=f.error_span(:reset_password_sent_at) %>
  </div>
  <div class="form-group">
    <%= f.label :remember_created_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :remember_created_at, :class => 'form-control' %>
    </div>
    <%=f.error_span(:remember_created_at) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:encrypted_password) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_token) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_sent_at) %></th>
      <th><%= model_class.human_attribute_name(:remember_created_at) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= user.encrypted_password %></td>
        <td><%= user.reset_password_token %></td>
        <td><%= user.reset_password_sent_at %></td>
        <td><%= user.remember_created_at %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:encrypted_password) %>:</strong></dt>
  <dd><%= @user.encrypted_password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reset_password_token) %>:</strong></dt>
  <dd><%= @user.reset_password_token %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reset_password_sent_at) %>:</strong></dt>
  <dd><%= @user.reset_password_sent_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:remember_created_at) %>:</strong></dt>
  <dd><%= @user.remember_created_at %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>